# Generated by Django 4.1.3 on 2022-12-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMetricsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('metric_name', models.CharField(choices=[('FR', 'Freshman'), ('Temperature', 'Температура'), ('Wind Speed', 'Скорость ветра')], max_length=35, verbose_name='Название метрики')),
                ('value', models.FloatField(blank=True, verbose_name='Значение')),
                ('date_and_time', models.DateTimeField(blank=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Скорость ветра',
                'verbose_name_plural': 'Все метрики скорости ветра',
                'ordering': ['-date_and_time'],
            },
        ),
    ]
