# Generated by Django 4.1.3 on 2022-12-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermetricsmodel',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
