# Generated by Django 4.1.3 on 2022-12-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_weathermetricsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathermetricsmodel',
            options={'ordering': ['-date_and_time'], 'verbose_name': 'Метрика погоды', 'verbose_name_plural': 'Метрики погоды'},
        ),
        migrations.AlterField(
            model_name='weathermetricsmodel',
            name='metric_name',
            field=models.CharField(choices=[('Temperature', 'Температура'), ('Precipitation', 'Осадки'), ('Wind Speed', 'Скорость ветра'), ('Wind Direction', 'Направление ветра')], max_length=25, verbose_name='Название метрики'),
        ),
    ]
