# Generated by Django 4.1.3 on 2022-12-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('metrics', '0003_alter_weathermetricsmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weathermetricsmodel',
            old_name='metric_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='weathermetricsmodel',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usercommentsmodel', verbose_name='Комментарий'),
        ),
    ]
