# Generated by Django 4.1.3 on 2022-12-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_rename_metric_name_weathermetricsmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathermetricsmodel',
            name='comments',
        ),
    ]
