# Generated by Django 4.1.3 on 2022-12-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_remove_weathermetricsmodel_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindSpeedModel',
        ),
    ]
