# Generated by Django 4.1.3 on 2022-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_delete_windspeedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermetricsmodel',
            name='date_and_time',
            field=models.DateField(blank=True, verbose_name='Дата и время'),
        ),
    ]
