# Generated by Django 4.1.3 on 2022-12-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_alter_weathermetricsmodel_date_and_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathermetricsmodel',
            options={'ordering': ['-date'], 'verbose_name': 'Метрика погоды', 'verbose_name_plural': 'Метрики погоды'},
        ),
        migrations.RemoveField(
            model_name='weathermetricsmodel',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='weathermetricsmodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='weathermetricsmodel',
            name='name',
            field=models.CharField(choices=[('Max Temperature', 'Максимальная температура'), ('Min Temperature', 'Минимальная температура'), ('Precipitation Sum', 'Сумма осадков'), ('Max Wind Speed', 'Максимальная скорость ветра'), ('Dominant Wind Direction', 'Господствующее направление ветра')], max_length=25, verbose_name='Название метрики'),
        ),
    ]
