# Generated by Django 4.1.3 on 2022-12-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_remove_weathermetricsmodel_comments'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommentsmodel',
            name='weather_metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.weathermetricsmodel', verbose_name='Метрика погоды'),
        ),
    ]
